# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - foodle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_804a3f8b22b44cd4a5c612b40d164fda }}
        password: ${{ secrets.AzureAppService_ContainerPassword_246be9e4f56543f1842baddc3bf22941 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_804a3f8b22b44cd4a5c612b40d164fda }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'foodle'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7bab738ae8b5485487adf43f1de849a5 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_804a3f8b22b44cd4a5c612b40d164fda }}/appsvc/staticsite:${{ github.sha }}'