# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - fihr-foodle

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_b85e694d053a4166853a8eea8c8a1152 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a92a75344fc6459da0cde6e6f2aa4698 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_b85e694d053a4166853a8eea8c8a1152 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fihr-foodle'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_95fab0cd5f10496e8da87c77bade6aca }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_b85e694d053a4166853a8eea8c8a1152 }}/appsvc/staticsite:${{ github.sha }}'